### PR TITLE
Custom background image for lock screen

### LINKED ISSUE #55: Option to change background of lock-screen
It would be really, really nice to see option to change background of lock-screen that MATE has. This feature would fit perfectly inside "Desktop Settings" window, accessible from Control Center :)
## 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/3460377-option-to-change-background-of-lock-screen?utm_campaign=plugin&utm_content=tracker%2F1635706&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1635706&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by rbuj**
closes #55

### CODE REVIEW

**Comment by milouse** [comment]
I agree with that PR. I have a simple workflow to explain it: I use a wallpaper manager, and each time my wallpaper changes, it creates a blurred copy of it, which is saved in an accessible place, to be used by LightDM. I would like my lock screen to use the same blurred picture, instead of my current background.

Thank you for your work!

**Comment by milouse** [comment]
I confirm this patch runs fine after several days. No unexpected things.

Maybe an improvement: could you make the new background picture for lockscreen be desactivated when the lock screen is desactivated (previous checkbox)? The two options will look more linked together.

Capture du 2020-03-25 19-35-26

**Comment by rbuj** [comment]
@milouse The screen can be locked in other ways, choosing System - Lock Screen from mate-panel classic menu.

Screenshot at 2020-03-25 20-23-17

**Comment by milouse** [comment]
Ho, yes, you're right! You can forgot my last comment.

**Comment by sc0w** [comment]
@milouse and you can do the same quikly with <kbd>ctrl</kbd><kbd>alt</kbd><kbd>L</kbd>

**Comment by raveit65** [comment]
I just updated fedora 32 and rawhide with PR.
https://bodhi.fedoraproject.org/updates/FEDORA-2020-edc02ca65b
Thanks again.

**Pull request merged**
