### PR TITLE
Set debug & warning flags using new mate-common macros

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
LGTM,
```
[rave@mother mate-screensaver-dist]$ ./autogen.sh 

        cflags:                   
        Warning flags:            -Wall -Wmissing-prototypes

[rave@mother mate-screensaver-dist]$ ./configure --enable-compile-warnings=no

        cflags:                   
        Warning flags:            

[rave@mother mate-screensaver-dist]$ ./configure --enable-compile-warnings=yes

        cflags:                   
        Warning flags:            -Wall -Wmissing-prototypes

[rave@mother mate-screensaver-dist]$ ./configure --enable-compile-warnings=maximum

        cflags:                   
        Warning flags:            -Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wno-sign-compare

[rave@mother mate-screensaver-dist]$ ./configure --enable-compile-warnings=error

        cflags:                   
        Warning flags:            -Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wno-sign-compare -Werror

[rave@mother mate-screensaver-dist]$ ./configure --enable-debug=yes

        cflags:                    -g -O0
        Warning flags:            -Wall -Wmissing-prototypes

[rave@mother mate-screensaver-dist]$ ./configure --enable-debug=info

        cflags:                    -g
        Warning flags:            -Wall -Wmissing-prototypes

[rave@mother mate-screensaver-dist]$ ./configure --enable-debug=profile

        cflags:                    -g -pg
        Warning flags:            -Wall -Wmissing-prototypes

[rave@mother mate-screensaver-dist]$ ./configure --enable-debug=no

        cflags:                   
        Warning flags:            -Wall -Wmissing-prototypes

[rave@mother mate-screensaver-dist]$ 
```
@rbuj 
I don't think we need the maintainer mode now, or?
```
Maintainer mode:          yes
```

**Comment by rbuj** [comment]
@sc0w We can keep AM_MAINTAINER_MODE, this macro is related to rebuild rules, such as checking file timestamps.

**Comment by raveit65** [comment]
Ok, than it is fine.
I recall that we removed the mode in another repo.

**Comment by rbuj** [comment]
@raveit65 I recall that we removed MAINTAINER_CFLAGS.

**Pull request merged**
