### PR TITLE
Corrected several icon translations (which broke the .desktop icons)

### PR DESCRIPTION
**Pull request by sebastianschauenburg**
This string should not be translated at all (and it's not available on Transifex for translation, I checked). Similar fix as https://github.com/mate-desktop/mate-screensaver/pull/240

### CODE REVIEW

**Comment by rbuj** [comment]
See #242

**Comment by sebastianschauenburg** [comment]
Added fixes for several other languages as well.

**Comment by sebastianschauenburg** [comment]
if there is any doubt about these changes, please read [my recent blogpost](https://www.schauenburg.nl/posts/2021/01/11_translators_-_please_do_not_translate_everything.html) about this specific enhancement

**Comment by sebastianschauenburg** [comment]
@rbuj seems like #242 is OK and has been merged. Could you do the same with this request please? :-)

**Comment by rbuj** [comment]
l10n: The translations are managed at https://www.transifex.com/mate/MATE/dashboard/.
We have already fixed this kind of issue on other MATE components, as we don't fetch the translation for the icon name.

**Comment by sebastianschauenburg** [comment]
@rbuj I checked the strings at Transifex and they were not present there anymore, currently. But in this repository, the .po files still contain the translated (or copied) strings, which seem incorrect? I'm fine with not accepting this pull request, but it would mean #242 should've also not been accepted, for consistency :wink:  Just tried to help out here.

**Comment by rbuj** [comment]
Even if the icon names are in the catalog they are not used for generating the desktop files.

**Pull request closed without merging**
