### PR TITLE
Add keywords key to .desktop files

### PR DESCRIPTION
**Pull request by flexiondotorg**
Taken from downstream Debian patch.

### CODE REVIEW

**Comment by rbuj** [comment]
Keywords key can be translated. Use `_Keywords=...` instead of `Keywords=`.

**Comment by flexiondotorg** [comment]
Thanks @rbuj, changed as suggested :+1:

**Comment by flexiondotorg** [comment]
Translator notes added.

**Comment by raveit65** [comment]
Merged without deleting the branch!

**Pull request merged**
