### PR TITLE
Add HiDPI support for lock screen

### PR DESCRIPTION
**Pull request by vkareh**
* Password dialog is now scaled
* Background of lock screen is now scaled

### CODE REVIEW

**Comment by raveit65** [comment]
But i see only changes for 'Password dialog' and 'Background of lock screen'.
The screensaver function itself (the themes) is(are) working with a HIDPI monitor?

**Comment by flexiondotorg** [comment]
I've only tested the MATE logo screen saver and that works correctly in HiDPI mode. I'll test a selection of screen savers today and report back.

**Comment by raveit65** [comment]
@flexiondotorg 
Did you use the rebase+merge Button ?
Still wondering why we have the PR number now in commit header...
https://github.com/mate-desktop/mate-screensaver/commit/c862d81db1e0ae1ce1f62a3aac1d915f5036c81c

**Comment by monsta** [comment]
It was "squash+merge" for sure - "rebase+merge" doesn't add that.

**Pull request merged**
