### PR TITLE
Fix: idle slider display bug

### LINKED ISSUE #101: idle slider display bug
The display timer is over the slider button (see pic's) 
This is the normal way 

And this is with the bug

Tested on Ubuntu MATE 16.10 daily with MATE 1.15 latest 
Reported to Ubuntu MATE launchpad https://bugs.launchpad.net/ubuntu-mate/+bug/1623196
## 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37898722-idle-slider-display-bug?utm_campaign=plugin&utm_content=tracker%2F1635706&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1635706&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sc0w**
Fixes #101

### CODE REVIEW

**Comment by raveit65** [comment]
This works well if time is under 1 hour and exactly 2 hours, but not for 1 hour to 2hours.
screensaver-ui-1
screensaver-ui-2
screensaver-ui-3

**Comment by sc0w** [comment]
it works fine here with LANG C

I think because "hours" and  "stunde" have different length

I will investigate to work with all langs

**Comment by raveit65** [comment]
Indeed, it works well with english :-)

**Comment by monsta** [comment]
I don't think it's possible to make this work in all locales...

**Comment by sc0w** [comment]
@raveit65 @monsta please test

commit rebased, now it works fine here with the languages C, ES, and DE, and I think it must work with all

**Comment by raveit65** [comment]
Fine with german ,french, vi_VN, uk_UA, pt_BR, pl_PL and zh_CN.
But minutes > 9 are broken with fi_FI

**Comment by sc0w** [comment]
@raveit65 please test again

with latest changes, it works here with:

id_ID, pt_BR, hy_AM, is_IS, it_IT, ja_JP, sr_RS, ko_KR, sl_SI, sk_SK, lt_LT, bg_BG, ru_RU, ms_MY

**Comment by monsta** [comment]
```
monsta@asylum:~/mate/mate-screensaver$ ls -l po/*.po | wc -l
93
```
That's a long way 😄

**Comment by sc0w** [comment]
@monsta no problem, I will test all :)

**Comment by sc0w** [comment]
tested and working:

```
  am_ET.UTF-8... done
  ar_SA.UTF-8... done
  as_IN.UTF-8... done
  ast_ES.UTF-8... done
  be_BY.UTF-8... done
  bg_BG.UTF-8... done
  bn_BD.UTF-8... done
  bn_IN.UTF-8... done
  br_FR.UTF-8... done
  bs_BA.UTF-8... done
  ca_ES.UTF-8... done
  ca_ES.UTF-8@valencia... done
  cmn_TW.UTF-8... done
  crh_UA.UTF-8... done
```

**Comment by raveit65** [comment]
fi_FI is fine now, thx for hard testing....

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/mate-screensaver/commit/52df89dc6ce7c3c58dcac6b781b8ff540336fce8
thx.

**Comment by sc0w** [comment]
@raveit65 

too fast, cy_GB doesn't work, I am testing to work in all

I will open new PR when I finish :)

**Comment by sc0w** [comment]
The fix to all languages: https://github.com/mate-desktop/mate-screensaver/pull/139

**Pull request closed without merging**
