### PR TITLE
mate-screensaver-preferences: fix memory leak

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
> @raveit65 I can ask them if you want me to...

Thanks to you feel responsible for a team task.

**Comment by mbkma** [comment]
@raveit65 a little bit late, but I wrote them today.

**Comment by raveit65** [comment]
> @raveit65 a little bit late, but I wrote them today.

Thank you, but i am really disappointed that other people here gives a fuck about. Maybe those guys thinks they are better developer than others and we have to do the unlikely tasks for them.....

**Comment by mbkma** [comment]
they already answered, we should have +25k credits again.

**Comment by mbkma** [comment]
@rbuj can you please repush to trigger the travis build?

**Comment by rbuj** [comment]
@mbkma done

**Review by mbkma — APPROVED** [review]
Works well and code looks good.

**Review by lukefromdc — APPROVED** [review]
The screensaver preferences dialog works fine with this built and installed. If something was being freed too soon I would expect a crash, and I got no such text in terminal running this from the terminal after killing the previous running instance of mate-screensaver and playing around with the various options in the preferences dialog. This seems to be ready to go

**Pull request merged**
